# ATEZO UNWEIGHTED 
DATA_PARAMS:
  drug: 'Atezo'
  gex_units: 'tpm'
  expression_path: "../data/expression/cri"

EXPERIMENT_PARAMS:
  rng_seed: 12345
  n_splits: 10 # not used for LOO or monte carlo
  shuffle: True
  models: ['most_frequent','uniform','stratified','LR','SVC','KNN','RBF']
  cv_score: 'balanced_accuracy'
  res_path: "../data/results/"
  split_type: 'stratified'
  n_trials: 100 # not used for kfold or LOO
  


GENESET_PARAMS:
  geneset_base: "../data/genesets/"
  genesets: ['auslander','LINCS','COSMIC','CD8T','TCE','CAF','TAM','GeneBio','target']
  target_cutoff: 200


NETWORK_PARAMS:
  network_base: "../data/networks/cri"
  network_types: ['sparse','dense']
  weightings: ['unweighted','unweighted']
