EXPERIMENT_PARAMS:
  drug: 'Atezo'
  rng_seed: 1234
  data_dir: "../data/expression/"
  rankcount_cutoff: 150
  pval_thresh: 0.01
  n_iters: 3 #100
  tissues: ['BLCA','KIRC']
  do_one_hop: True

  
  
NETWORK_PARAMS:
  edge_types: ['weighted']
  connectivity: ['tight']
  normalization: 'MAX'

WAVELET_PARAMS:
  J: 3
  p: 4
  central: False
  wavelet_type: 'Diffusion'


MODEL_PARAMS:
  model: 'LR'
  preproc: ['robust'] #,'standardize','center']
  cv_criterion: 'roc_auc'
