EXPERIMENT_PARAMS:
  drug: 'sorafenib'
  tissues: ['BRCA','LUAD','SKCM']
  rng_seed: 1234
  data_dir: "../data/expression/ccle/"
  num_iters: 100
  train_percentage: 0.8
  feature_columns: []
  feature_file_name: 'metab_features'


MODEL_PARAMS:
  models: ['LR','KNN']
  cv_criterion: 'roc_auc'


PAUCITY_PARAMS:
  min_train_percent: 0.70
  max_train_percent: 0.95
  step_size: 0.05
  round_value: 2
