EXPERIMENT_PARAMS:
  drug: 'Pembro'
  rng_seed: 1234
  data_dir: "../data/expression/"
  rankcount_cutoff: 100
  fdr_string: 'medium'
  n_iters: 10
  do_one_hop: False

  
  
NETWORK_PARAMS:
  edge_types: ['weighted']
  connectivity: ['sparse']

WAVELET_PARAMS:
  J: 3
  p: 4
  central: True


MODEL_PARAMS:
  model: 'LR'
  preproc: 'standardize'
  cv_criterion: 'roc_auc'
